### ISSUE TITLE
No class on element

### ISSUE THREAD

**Issue by eadz** [gajus/react-css-modules-examples#1]
Hey,

Maybe I'm doing something wrong, but I get no styles or classes on the elements. ( Chrome, OSX ). 

No warnings in the console either. 

<img width="377" alt="screen shot 2015-08-28 at 12 51 47 am" src="https://cloud.githubusercontent.com/assets/11939/9536037/55f67540-4d1f-11e5-8d5a-17e373dd9643.png">

**Comment by gajus** [comment]
Did you literally follow the instructions?

```
git clone https://github.com/gajus/react-css-modules-examples.git
cd ./react-css-modules-examples
npm install
webpack-dev-server
```

**Comment by gajus** [comment]
Assuming you have, please create a repository and commit your working directory, including the "node_modules" directory.

**Comment by eadz** [comment]
@gajus Thanks for your help. Yep, I just followed those instructions. 

I actually felt bad about by bug report, as I should do some digging myself. I'm not a js programmer by trade, and this stuff is pretty magic, so it's a bit of a challenge. 

Anyway, I changed the version of   "react-css-modules" to 3.0.1 in the package.json and now it works :)

**Comment by gajus** [comment]
Thanks. I updated the package.json.
