### ISSUE TITLE
Usage with third party css framework

### ISSUE THREAD

**Issue by roylee0704** [gajus/react-css-modules-examples#4]
Firstly, thanks for the awesome work :)

I have a question here, its regarding on how do I use this together with 3rd party css framework like: `bootstraps`, `flexboxgrid`, `semantic-ui`?

**Comment by gajus** [comment]
Try searching the existing issues.

**Comment by gajus** [comment]
https://github.com/gajus/react-css-modules/issues/57#issuecomment-159255217
