### ISSUE TITLE
Hot loading not working on Chrome/Windows.

### ISSUE THREAD

**Issue by jedmao** [gajus/react-css-modules-examples#5]
I ran `./node_modules/.bin/webpack-dev-server` and when I make CSS changes they don't hot load on Chrome/Windows.

**Comment by gajus** [comment]
They are not supposed to. Search for existing issues and you will find an explanation and a solution.

**Comment by gajus** [comment]
See:

* https://github.com/gajus/react-css-modules#react-hot-module-replacement
* https://github.com/gajus/react-css-modules/issues/51
