### ISSUE TITLE
Possible to get it working if CSS filename contains hash?

### ISSUE THREAD

**Issue by F21** [gajus/react-css-modules-examples#6]
I have the extract test plugin configured to produce a hashed filename to do reloads with browsersync:

```javascript
new plugins.extractText('[id].[contenthash].css', { allChunks: true })
```

Unfortunately, unless the filename is set to something static like `app.css`, the reloading doesn't work.

Would it be possible to get the reloading to work with a hashed filename? I understand that this may be a bit difficult, because I think browsersync does the reloading by matching the filename.

**Comment by gajus** [comment]
Whats the reason for having this configuration in the development setup?

**Comment by F21** [comment]
I wanted dev to be as close to prod as possible.

**Comment by gajus** [comment]
Hashes are designed to be used specifically in production. No, there is no way I can think of to make it work using configuration alone.

**Comment by F21** [comment]
I've decided to only use the extracttextplugin in prod as well. I have slower disks, so writing to disk can be a bit slower.
