### ISSUE TITLE
Problems installing the examples

### ISSUE THREAD

**Issue by steven-fernandez** [gajus/react-css-modules-examples#8]
I have followed the instructions you gave to download and install and I keep getting this error on my console:

> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
>  - configuration has an unknown property 'debug'. These properties are valid:
>    object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
>    The 'debug' property was removed in webpack 2.
>    Loaders should be updated to allow passing this option via loader options in module.rules.
>    Until loaders are updated one can use the LoaderOptionsPlugin to switch loaders into debug mode:
>    plugins: [
>      new webpack.LoaderOptionsPlugin({
>        debug: true
>      })
>    ]
>  - configuration.resolve.extensions[0] should not be empty.

How can I fix this?

**Comment by gajus** [comment]
> configuration has an unknown property 'debug'. These properties are valid:

Remove "debug" property.

**Comment by steven-fernandez** [comment]
From where?

**Comment by gajus** [comment]
> The 'debug' property was removed in webpack 2.

"webpack"
